### ISSUE TITLE
Password authentication failure in fetch_data.py

### ISSUE THREAD

**Issue by fredcallaway** [fredcallaway/psirokuturk#18]
(From Jonathan)

I’m getting a bizarre error when I go to fetch the data from my experiment (running bin/fetch_data.py version; this has been working completely fine until now).
```
psycopg2.OperationalError: connection to server at "ec2-44-215-1-253.compute-1.amazonaws.com" (44.215.1.253), port 5432 failed: FATAL:  password authentication failed for user "pecjzmgvmcffme"
connection to server at "ec2-44-215-1-253.compute-1.amazonaws.com" (44.215.1.253), port 5432 failed: FATAL:  no pg_hba.conf entry for host "84.33.153.8", user "pecjzmgvmcffme", database "d1gh6l0jffv33e", no encryption
```

**Comment by fredcallaway** [comment]
@jonathanicholas

I am not able to reproduce this error with a fresh clone of your fork (https://github.com/jonathanicholas/feat-bandit)

**Comment by jonathanicholas** [comment]
I deleted .database_url and it fixed it. not sure what happened, but that's the fix if anyone encounters something like this in the future

**Comment by fredcallaway** [comment]
Ah okay that makes sense. Fixed by  092fa0364931e9314509327dff3889a5f7ca2fd9

**Comment by jonathanicholas** [comment]
but so somehow the actual url became different from that saved by previous runs of the fetch_data script. Is that something the automatic heroku updates may do?

**Comment by fredcallaway** [comment]
Yes I think Heroku must have your database URL. It's not a common thing though, certainly not with every database update (in my experience at least).
