### ISSUE TITLE
add hyperbatching

### ISSUE THREAD

**Issue by jcpeterson** [fredcallaway/psirokuturk#2]
Essential feature request: Emulate TurkPrime's (now "Cloud Research") HyperBatch feature to avoid accruing an extra 20% MTurk fee for having more than 9 subjects / HIT. I've used TurkPrime quite a bit. The feature is tried-and-true, but there's a fee for it (smaller than the 20% amazon fee but still worth avoiding). 

See:
https://gist.github.com/deargle/f454a156d3a72adf62869e2ef09101d8
https://github.com/ddbourgin/mturk_utils

**Comment by fredcallaway** [comment]
This would be nice, but it should be implemented in psiturk itself. Note that you can achieve this effect quite easily by simply copying the hit creation command many times. In a text editor, create a file like this, where it repeats as many times as necessary to get to the total number of assignments you want. Then copy the whole thing and paste it into the psiturk prompt. Elegant? No. Effective? Yes.

hit create 9 1.25 0.5
y

hit create 9 1.25 0.5
y

hit create 9 1.25 0.5
y

...
