### ISSUE TITLE
Building with JsPsych

### ISSUE THREAD

**Issue by Sahaj09** [fredcallaway/psirokuturk#6]
Can we build an experiment using JsPsych that functions using Psiturk and Heroku with a similar structure?

**Comment by cgc** [comment]
Hello @Sahaj09, have you had a chance to run the project and take a look at it? At present the example code we have is for jsPsych. You can modify the experiment by changing the `experiment.js` file ([link here](https://github.com/fredcallaway/psirokuturk/blob/master/static/js/experiment.js)). You can see the jsPsych plugins that are currently loaded on the `exp.html` template ([link here](https://github.com/fredcallaway/psirokuturk/blob/master/templates/exp.html)). The documentation is a bit sparse, so do let us know if you have any issues getting things running.
